version: '3.1'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/etc/nginx/html
